# Generated by Django 4.2.6 on 2023-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('inp_dttm', models.DateTimeField(auto_now=True, db_column='INP_DTTM', db_comment='입력일시', null=True)),
                ('upd_dttm', models.DateTimeField(auto_now_add=True, db_column='UPD_DTTM', db_comment='수정일시', null=True)),
                ('ctnt_no', models.AutoField(db_column='CTNT_NO', db_comment='콘텐츠 번호', primary_key=True, serialize=False)),
                ('ctnt_title', models.CharField(blank=True, db_column='CTNT_TITLE', db_comment='콘텐츠 제목', max_length=100, null=True)),
                ('ctnt_subtitle', models.CharField(blank=True, db_column='CTNT_SUBTITLE', db_comment='콘텐츠 소제목', max_length=150, null=True)),
                ('inp_user', models.CharField(blank=True, db_column='INP_USER', db_comment='생성자', max_length=30, null=True)),
            ],
            options={
                'db_table': 'contents_mst',
                'db_table_comment': '컨텐츠 정보 테이블',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentsDetail',
            fields=[
                ('inp_dttm', models.DateTimeField(auto_now=True, db_column='INP_DTTM', db_comment='입력일시', null=True)),
                ('upd_dttm', models.DateTimeField(auto_now_add=True, db_column='UPD_DTTM', db_comment='수정일시', null=True)),
                ('ctnt_no', models.AutoField(db_column='CTNT_NO', db_comment='콘텐츠 번호', primary_key=True, serialize=False)),
                ('ctnt_title', models.CharField(blank=True, db_column='CTNT_TITLE', db_comment='콘텐츠 제목', max_length=100, null=True)),
                ('ctnt_path', models.CharField(blank=True, db_column='CTNT_PATH', db_comment='콘텐츠 파일 경로', max_length=200, null=True)),
                ('ctnt_name', models.CharField(blank=True, db_column='CTNT_NAME', db_comment='콘텐츠 파일 이름', max_length=200, null=True)),
                ('ctnt_ext', models.CharField(blank=True, db_column='CTNT_EXT', db_comment='콘텐츠 파일 확장자', max_length=200, null=True)),
                ('inp_user', models.CharField(blank=True, db_column='INP_USER', db_comment='생성자', max_length=30, null=True)),
            ],
            options={
                'db_table': 'contents_dtl',
                'db_table_comment': '컨텐츠 상세정보 테이블',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentsTags',
            fields=[
                ('tag_no', models.AutoField(db_column='TAG_NO', db_comment='태그 번호', primary_key=True, serialize=False)),
                ('ctnt_no', models.IntegerField(blank=True, db_column='CTNT_NO', db_comment='콘텐츠 번호', null=True)),
                ('sort', models.IntegerField(blank=True, db_column='SORT', db_comment='태그 정렬 순서', null=True)),
            ],
            options={
                'db_table': 'contents_tags',
                'db_table_comment': '컨텐츠 태그 정보 테이블',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('inp_dttm', models.DateTimeField(auto_now=True, db_column='INP_DTTM', db_comment='입력일시', null=True)),
                ('upd_dttm', models.DateTimeField(auto_now_add=True, db_column='UPD_DTTM', db_comment='수정일시', null=True)),
                ('file_no', models.AutoField(db_column='FILE_NO', db_comment='콘텐츠 제목', primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, db_column='FILE_PATH', db_comment='파일 경로', max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, db_column='FILE_NAME', db_comment='파일 이름', max_length=200, null=True)),
                ('file_ext', models.CharField(blank=True, db_column='FILE_EXT', db_comment='파일 확장자', max_length=200, null=True)),
                ('ctnt_no', models.IntegerField(blank=True, db_column='CTNT_NO', db_comment='콘텐츠 번호', null=True)),
            ],
            options={
                'db_table': 'file_mst',
                'db_table_comment': '컨텐츠 첨부파일 정보 테이블',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('inp_dttm', models.DateTimeField(auto_now=True, db_column='INP_DTTM', db_comment='입력일시', null=True)),
                ('upd_dttm', models.DateTimeField(auto_now_add=True, db_column='UPD_DTTM', db_comment='수정일시', null=True)),
                ('tag_no', models.AutoField(db_column='TAG_NO', db_comment='태그 번호', primary_key=True, serialize=False)),
                ('tag_name', models.CharField(blank=True, db_column='TAG_NAME', db_comment='태그 이름', max_length=15, null=True)),
            ],
            options={
                'db_table': 'tags_mst',
                'db_table_comment': '태그 정보 테이블',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('inp_dttm', models.DateTimeField(auto_now=True, db_column='INP_DTTM', db_comment='입력일시', null=True)),
                ('upd_dttm', models.DateTimeField(auto_now_add=True, db_column='UPD_DTTM', db_comment='수정일시', null=True)),
                ('user_no', models.AutoField(db_column='USER_NO', db_comment='유저번호', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='USERNAME', db_comment='유저명', max_length=30, null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', db_comment='비밀번호', max_length=100, null=True)),
                ('grant', models.CharField(blank=True, db_column='GRANT', db_comment='사용자 권한', max_length=10, null=True)),
            ],
            options={
                'db_table': 'user_mst',
                'db_table_comment': '사용자 정보 테이블',
                'managed': False,
            },
        ),
    ]
