# Generated by Django 4.2.6 on 2023-10-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('inp_dttm', models.DateTimeField(auto_now=True, db_column='INP_DTTM', db_comment='입력일시', null=True)),
                ('upd_dttm', models.DateTimeField(auto_now_add=True, db_column='UPD_DTTM', db_comment='수정일시', null=True)),
                ('ctnt_no', models.AutoField(db_column='CTNT_NO', db_comment='콘텐츠 번호', primary_key=True, serialize=False)),
                ('ctnt_title', models.CharField(blank=True, db_column='CTNT_TITLE', db_comment='콘텐츠 제목', max_length=100, null=True)),
                ('ctnt_subtitle', models.CharField(blank=True, db_column='CTNT_SUBTITLE', db_comment='콘텐츠 소제목', max_length=150, null=True)),
                ('inp_user', models.CharField(blank=True, db_column='INP_USER', db_comment='생성자', max_length=30, null=True)),
            ],
            options={
                'db_table': 'contents_mst',
                'db_table_comment': '컨텐츠 정보 테이블',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentsTag',
            fields=[
                ('tag_no', models.AutoField(db_column='TAG_NO', db_comment='태그 번호', primary_key=True, serialize=False)),
                ('ctnt_no', models.IntegerField(blank=True, db_column='CTNT_NO', db_comment='콘텐츠 번호', null=True)),
                ('sort', models.IntegerField(blank=True, db_column='SORT', db_comment='태그 정렬 순서', null=True)),
            ],
            options={
                'db_table': 'contents_tags',
                'db_table_comment': '컨텐츠 태그 정보 테이블',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('inp_dttm', models.DateTimeField(auto_now=True, db_column='INP_DTTM', db_comment='입력일시', null=True)),
                ('upd_dttm', models.DateTimeField(auto_now_add=True, db_column='UPD_DTTM', db_comment='수정일시', null=True)),
                ('tag_no', models.AutoField(db_column='TAG_NO', db_comment='태그 번호', primary_key=True, serialize=False)),
                ('tag_name', models.CharField(blank=True, db_column='TAG_NAME', db_comment='태그 이름', max_length=15, null=True)),
            ],
            options={
                'db_table': 'tags_mst',
                'db_table_comment': '태그 정보 테이블',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contents',
        ),
        migrations.DeleteModel(
            name='ContentsTags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
