# Generated by Django 4.1.13 on 2023-11-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_content_ctnt_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsdetail',
            name='ctnt_dtl_inp_user',
            field=models.CharField(blank=True, db_column='INP_USER', max_length=300, null=True),
        ),
    ]
